### ISSUE TITLE
State variable shape not shown in SBGN

### ISSUE THREAD

**Issue by ibalaur** [sbgn/ySBGN#15]
For the Mevalonate diagram (Metabolism Regulation Project - http://metabolismregulation.org/), state variables for CaM are not shown right in the output SBGN due to negative coordinates for "y". 
Please test using the F003-mevalonate.graphml and/or F003-mevalonate-V002.graphml from http://metabolismregulation.org/mevalonate/.

**Comment by ibalaur** [comment]
Also, please see state variables for HSL from F015-tag: http://metabolismregulation.org/tag/

**Comment by amazein** [comment]
F003 and F015 cases are corrected by moving the whole map to make all coordinates positive values. Uploaded to downloads to replace previous versions.
I think this type should be corrected automatically for the whole maps: simply changing all coordinates. Then it will be okay in SBGN-ED too.
