### ISSUE TITLE
Units of information are duplicated for multimer

### ISSUE THREAD

**Issue by ibalaur** [sbgn/ySBGN#16]
Units of information are considered twice in case of multimers. Please see the attached based on http://metabolismregulation.org/glycolysis/.
[F001-glycolysis_test_case.graphml.zip](https://github.com/sbgn/ySBGN/files/3051675/F001-glycolysis_test_case.graphml.zip)

**Comment by amazein** [comment]
Not sure what you mean. Looks okay. Do you mean there is a hidden unit of information, a copy of the one we see? I transformed into shapes in yEd, still looks fine, no duplicated shapes.

**Comment by ibalaur** [comment]
This was fix by: https://github.com/sbgn/ySBGN/commit/d679abe0231bdf8ff645920fa7c41ff2c63445a2
Please see updated release https://github.com/sbgn/ySBGN/releases/tag/1.2-alpha
